services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: servicios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: esmiacc123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maven:
    image: maven:3.9.9-eclipse-temurin-17
    container_name: maven_container
    working_dir: /app
    volumes:
      - ./sistema-de-cliente:/app
    command: mvn clean package

  cliente:
    build:
      context: ./sistema-de-cliente
      dockerfile: Dockerfile
    container_name: cliente_container
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  inventario:
    build:
      context: ./sistema-de-inventario
      dockerfile: Dockerfile
    container_name: inventario_container
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  ventas:
    build:
      context: ./sistema-de-ventas
      dockerfile: Dockerfile
    container_name: ventas_container
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - cliente
      - inventario

  logistica:
    build:
      context: ./sistema-de-logistica
      dockerfile: Dockerfile
    container_name: logistica_container
    ports:
      - "8084:8084"
    depends_on:
      - postgres

  administracion:
    build:
      context: ./sistema-de-administracion
      dockerfile: Dockerfile
    container_name: administracion_container
    ports:
      - "8085:8085"
    depends_on:
      - postgres

  web:
    build:
      context: ./sistema-de-web
      dockerfile: Dockerfile
    container_name: web_container
    ports:
      - "8086:8086"
    depends_on: []

volumes:
  postgres_data: